# https://docs.docker.com/compose/compose-file/compose-file-v3/
# https://devhints.io/docker-compose

services:
  
  bitmex_streamer:
    container_name: bitmex_streamer
    build:
      context: .
      dockerfile: bitmex_streamer/Dockerfile
    env_file: .env
    restart: always

  trading_algorithm:
    container_name: trading_algorithm
    build:
      context: .
      dockerfile: trading_algorithm/Dockerfile
    network_mode: container:bitmex_streamer
    env_file: .env 
    depends_on:
      - bitmex_streamer
    restart: always
 



